### ISSUE TITLE
Sprockets now requires Sass (and it did not)

### ISSUE THREAD

**Issue by claudiob** [rails/sprockets#126]
Because of [this commit](https://github.com/rails/sprockets/commit/bc094ea193e4a562a2d285e522e3ed771b8adb3d) and [this commit](https://github.com/rails/sprockets/commit/873476abe21e87ef7a5d9ec3adbee80a7133d99b), Sprockets on master now requires the `sass` library.

Since Rails master depends on Sprockets master, upgrading any existing Rails app to edge Rails will cause an error if the app uses sprockets but not sass.

I believe this is an issue… you should be able to use sprockets without having `sass` installed.
Let me know if I can help :ribbon:

**Comment by rafaelfranca** [comment]
Only the second commit is the cause of the issue :smile:

**Comment by Andreis13** [comment]
I believe this is because we had to define a custom importer that inherits from Sass::Importers::Filesystem. Sprokets has to load sass when registering the processors which depend on this importer definition.

One solution, as I see it, would be to drop support of sass-3.3 (3.4+ doesn't require this hack). Otherwise we could rethink the preconfiguration process like what processors get registered by default (maybe provide an interface for switching them on/off). In the Sprockets+Rails+Sass setup the registered sass processor gets overridden anyway by sass-rails.

One more way to do this is to define the importer inline (the class has only one placeholder method) so that the code gets evaluated only when it is actually used.

What do you think would be best?

**Comment by rafaelfranca** [comment]
Lets just drop support of sass 3.3

**Comment by jeremy** [comment]
:+1:
