### ISSUE TITLE
Changelog entries for 3.3.X versions

### ISSUE THREAD

**Issue by zachallaun** [rails/sprockets#128]
The 3.3.X versions of Sprockets introduced a number of changes and incompatibilities (that were subsequently fixed), including fixing caching on platforms like Heroku (thanks @schneems!).

I generally rely on changelogs to know what I'm getting into and whether it's worth upgrading to newer versions of things, and it would be great to see these improvements documented. It's likely also worth including a warning not to use e.g. 3.3.3, which seemed to have an issue where the cache wasn't being correctly busted when certain assets changed.

**Comment by wlipa** [comment]
I noticed that staleness problem with 3.3.3 as well, but didn't track it down.  Is it really fixed in 3.3.4?

**Comment by zachallaun** [comment]
@wlipa #127 suggests that it's indeed fixed in 3.3.4. @schneems would know more.

**Comment by connorshea** [comment]
And 3.4.0? Why aren't changelogs being released?

**Comment by schneems** [comment]
The problem is that we've got two main branches in active development right now. 3.x and master (which is effectively 4.x) it is very cumbersome to port changelogs from 3.x to master. If you need to see a changelog for the 3 series. I suggest you look in that branch. Maybe someone can add that info to the top of the readme in a PR? You could also help out by porting some of the changelog entries to from 3.x to the master branch. We're not working with a lot of firepower on sprockets core (TM) any help would be appreciated.

**Comment by zachallaun** [comment]
Thanks for the explanation! [Link to the 3.x changelog](https://github.com/rails/sprockets/blob/3.x/CHANGELOG.md), for anyone interested.

**Comment by rafaelfranca** [comment]
Yeah, CHANGELOG entries for the 3.x series is at the 3.x branch https://github.com/rails/sprockets/blob/3.x/CHANGELOG.md. I don't think it is a good idea to keep master branch in sync with 3.x changelogs. In fact I really wish to :fire: the CHANGELOG.md file in favor of github releases page like I did with sprockets-rails https://github.com/rails/sprockets-rails/releases
