### ISSUE TITLE
rake assets:precompile does not replace files whose permissions have changed

### ISSUE THREAD

**Issue by rafaelfranca** [rails/sprockets#137]
_From @trevorfrese on September 17, 2015 17:57_

Steps to reproduce: 
> touch assets/blah.txt 
> chmod 600 assets/blah.txt
> rake assets:precompile
Check public/assets for permissions on blah.txt 
> chmod 644 assets/blah.txt
> rake assets:precompile
Verify that public/assets permissions on blah.txt have not changed

Is rake assets:precompile not supposed to replace files when the permissions change? Is this an intentional design decision? And if so, can you explain why? 

Thanks! 

_Copied from original issue: rails/rails#21656_

**Comment by rafaelfranca** [comment]
_From @schneems on September 17, 2015 18:12_

Can you give me an app that reproduces the behavior using the latest released version of rails?

Sprockets uses mtime to determine when assets have changed, I would assume that chmod would change a file's mtime.

**Comment by rafaelfranca** [comment]
_From @trevorfrese on September 17, 2015 18:31_

Both of the rails apps I'm working on are private apps. Should I create an app with rails 4 to prove it? 

But on a side note, I just tested in terminal on an OS X Mac that using chmod does not change a file's modified time. Is this machine specific? Perhaps on linux distr's chmod changes modified time, but on OS X it doesn't appear to. 
![tfrese_ _bash_ _80x24_and_sessions_controller_test_rb_-_web_-____invoca_web_](https://cloud.githubusercontent.com/assets/1146935/9942368/842ec0f0-5d2f-11e5-82e8-de9232cb6794.png)

**Comment by rafaelfranca** [comment]
_From @al2o3cr on September 17, 2015 18:53_

Changing a file's permissions with `chmod` is going to alter the ctime, but not the mtime:

http://www.unix.com/tips-and-tutorials/20526-mtime-ctime-atime.html

Unless you've aliased `ls` to already include `-c`, you can see the difference with `ls -l` (shows mtime) vs `ls -lc` (shows ctime).

**Comment by rafaelfranca** [comment]
_From @trevorfrese on September 17, 2015 19:1_

So then according to what @al2o3cr  is saying, shouldn't `precompile` use a files ctime, instead of the mtime, to determine when assets have changed? Again - asking from a design perspective is this an intentional design decision?

**Comment by rafaelfranca** [comment]
I believe we can't use `ctime` because:

1) It only change when some metadata changes, and it will not change when the content changes.
2) In Windows it will not work because it return the creation time

https://en.wikipedia.org/wiki/MAC_times

**Comment by trevorfrese** [comment]
I think the first item you listed was incorrect. Once again, by testing it in my terminal it appears the `ctime` does in fact change when the file content changes, as so:
<img width="426" alt="tfrese_ _bash_ _202x43" src="https://cloud.githubusercontent.com/assets/1146935/9952466/cbde4a8c-5d8a-11e5-90a5-3a4ca6207fe3.png">

`ls -lc` displays the `ctime` on the far right, whereas `ls -l` displays the `mtime` on the far right. As you can see, when I change the permissions on the file to 777, the `mtime` remains `22:19` and the `ctime` becomes `22:21`. But when I modify the file contents and change them by appending to the file, the new `mtime` is `22:22` and the `ctime` as well is `22:22`, which proves that `ctime` takes into account the same changes as `mtime`, but also takes into account metadata changes as well. 

In response to your 2nd comment involving it not working on Windows: the current solution is not working on Mac though. Isn't that a problem already? Is there no Windows specific code in sprockets as well? Because as I'm researching it, `ctime, mtime, and atime` seem to be all Unix derivatives, and if Windows doesn't support these, how are you currently handling the case of `precompile` for Windows?

Thanks,
Trevor

**Comment by daniel-rikowski** [comment]
> Because as I'm researching it, ctime, mtime, and atime seem to be all Unix derivatives, and if Windows doesn't support these, how are you currently handling the case of precompile for Windows?

Ruby maps these functions to (mostly) equivalent Windows functions. `mtime` for example is implemented by calling `CreateFile` and `SetFileTime`.

Unfortunately some things are different, which for example created this Windows-specific problem with multithreaded servers: https://github.com/rails/sprockets/issues/136 (tl;dr: On Windows the file times cannot be changed when the file is currently open. On Linux it is allowed)

**Comment by trevorfrese** [comment]
>Ruby maps these functions to (mostly) equivalent Windows functions. mtime for example is >implemented via SetFileTime.

Daniel can you show me where in Ruby this is implemented? Because if `mtime` is implemented via `SetFileTime` as you are suggesting, then wouldn't `ctime` also be implemented via `SetFileTime`?

**Comment by daniel-rikowski** [comment]
I'm sorry, I mis-read your post and confused `mtime` which *reads* the modification time with `utime` which *writes* the modification (and access) time.

Let's try this again :)

`utime`, i.e. writing, is handled by [`SetFileTime`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724933%28v=vs.85%29.aspx). ([Code](https://github.com/ruby/ruby/blob/70b2af3b211f9746a5f9fe6bd76cc0fff3fbe2b0/win32/win32.c#L7129))
`ctime`, `mtime` and `atime` are read by [GetFileAttributesExW](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364946%28v=vs.85%29.aspx) ([Code](https://github.com/ruby/ruby/blob/70b2af3b211f9746a5f9fe6bd76cc0fff3fbe2b0/win32/win32.c#L5448))

As you can see in [lines L5464 to L5466](https://github.com/ruby/ruby/blob/70b2af3b211f9746a5f9fe6bd76cc0fff3fbe2b0/win32/win32.c#L5464) the  `[a|c|m]time` members of the stat structure are initialized with the equivalent values from the [WIN32_FILE_ATTRIBUTE_DATA ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365739%28v=vs.85%29.aspx) structure. Note that there is no real `ctime` in Windows, instead the creation time is used (which would be `crtime` in Linux/ext4 terms)

I guess it would be possible to use the maximum of `ctime` and `mtime`. That way it wouldn't matter if an OS/FS also updates `mtime` whenever `ctime` is changed. It also wouldn't matter that on Windows the creation time is returned. But I don't if reading *two* values that would hurt performance. On Windows reading file attributes is a pretty expensive operation.

**Comment by trevorfrese** [comment]
Thanks for the clarification and the code to back it up! This makes a LOT more sense now and I understand the decision as to why `mtime` was chosen, since it will work for Windows, Linux, and Mac by virtue of being shared between Linux and Mac, and shared by Windows. Whereas `ctime` doesn't have an equivalent on Windows, and the `ctime` they use is just the file creation time, which there is no equivalent for in Unix. 

Isn't there a simpler solution here? It seems like Mac and Linux do things one way, and Windows do things another way. Wouldn't it be better to therefore have 2 separate solutions, one for Linux and Mac reading from `ctime` and the other for Windows reading from `mtime` ? It seems like the current solution of just blindly using `mtime` since it happens to *almost* be correct for each OS is attempting to kill 2 birds with 1 stone. Your solution is slightly better because it at least would draw the correct value at all times, but it comes at the performance cost of doing 2 reads for each OS, even though in all cases for Linux and Mac `ctime` will be correct, and it would only really be solving the case for Windows, for which, `mtime` would be correct. 

Thoughts?

**Comment by rafaelfranca** [comment]
Nice investigation @daniel-rikowski! Yes, maximum ctime/mtime should work cross platform.

**Comment by rafaelfranca** [comment]
Conditionally calling one of the methods also works.

**Comment by trevorfrese** [comment]
It comes at less of a performance cost, I think it would be the more optimal choice, but I would like to hear Daniel's response as well. 
I leave the decision up to you of course.

**Comment by daniel-rikowski** [comment]
I did some benchmarks and I believe it is possible without any performance hit at all: Instead of individual calls to `File#mtime` and `File#ctime` we can just read all attributes at once with [`File#stat`](http://ruby-doc.org/core-2.2.0/File.html#method-c-stat) and then access the [`File::Stat`](http://ruby-doc.org/core-2.2.0/File/Stat.html) members.

Benchmarks:
```ruby
Benchmark.measure { 10_000.times { File.mtime('sample.txt') } }
Benchmark.measure { 10_000.times { File.mtime('sample.txt'); File.ctime('sample.txt') } }
Benchmark.measure { 10_000.times { File.stat('sample.txt') } }
```
Windows 10 (NTFS, SSD)
```
  0.063000   0.140000   0.203000 (  0.200460)
  0.062000   0.344000   0.406000 (  0.400572)
  0.047000   0.156000   0.203000 (  0.202252)
```

CentOS 7 (XFS, HDD)
```
  0.000000   0.010000   0.010000 (  0.006348)
  0.010000   0.000000   0.010000 (  0.011835)
  0.000000   0.000000   0.000000 (  0.006936)
```

**Comment by trevorfrese** [comment]
That looks very promising! I think `File#stat` is the best solution here, if it works in a similar manner to the Linux system call [stat](http://linux.die.net/man/2/stat), which gives the file's status. 
The fact that the speed is almost identical to hitting the `mtime` attribute is great, the only downside is that we are now taking slightly more memory per hit, since the `stat` object contains more data than technically necessary here. 
Comes down to a performance vs. memory question, but the FileStat objects are not very large, all 3 times I ran it the FileStat object was 144 bytes. 
<img width="1424" alt="tfrese_ _ruby_ _202x43_and_tfrese" src="https://cloud.githubusercontent.com/assets/1146935/9973261/81c8cf7c-5e24-11e5-8476-0b73b9e1a679.png">

And if one were to call FileStat, then it makes the most sense to use the solution Daniel proposed of simply taking the max of `stat.ctime` and `stat.mtime`, because that would be the most readable solution and it doesn't look as janky as having something along the lines of `if(Windows) use stat.mtime else use stat.ctime` 

Furthermore there may even be some branch prediction that takes place under the hood here that would speed up the conditional choices for the max method, in that it would be fairly certain that `stat.ctime` would be chosen on Linux and Mac, and fairly certain that `stat.mtime` would be chosen on Windows.

**Comment by schneems** [comment]
Happy to take a patch here. Otherwise it's been over a year, going to close.
