### ISSUE TITLE
Directives can't require absolute paths

### ISSUE THREAD

**Issue by vincentwoo** [rails/sprockets#25]
With [this commit](https://github.com/rails/sprockets/commit/6ef58208b1cbab973141ebe271e1293221453086), and the release of 3.0, it's become difficult to write a directive to resolve a config file as a dependency.

Previously I'd been using something like https://gist.github.com/dylanjha/11233766#file-0-sprockets_depend_on_config-rb to mark `config/file.yml` as a dependency, but it seems that sprockets 3.0 definitely doesn't want me to do that now. Is there a suggested path for achieving this in the new world?

**Comment by vincentwoo** [comment]
Ah, I suppose, upon further digging, the thing to do now is add an additional load path and use a standard `depend_on`?

**Comment by josh** [comment]
6ef58208b1cbab973141ebe271e1293221453086 was meant to prevent stuff like `//= require /etc/passwd`. `Context#depend_on` should still allow you to use a filename outside the load path. You're example seems like something that would work.

Though, I think a more preferred way of doing this would to not use a new `depend_on_config` directive. Manually declaring dependencies is a code smell.

It'd be better if your `output_locale` helper called `depend_on` with the specific .yml file it read from disk. That can work nicely if your output_locale is mixed into the context itself. https://github.com/rails/sprockets/blob/master/lib/sprockets/context.rb#L12-L15

Instead of 

``` js
//= depend_on_config 'locales/es.yml'
 
I18n.translations = I18n.translations || {};
I18n.translations.en = "<%= JsLocaleHelper.output_locale(:en) %>"
```

``` js
I18n.translations = I18n.translations || {};
I18n.translations.en = "<%= output_locale(:en) %>"
```

can just work

**Comment by vincentwoo** [comment]
Hm, interesting point. The problem with the old snippet is that `.context` appears to be no longer available in the Directive class, for some reason.

It's difficult for me to write a custom output handler in this particular case (I need to set globals for consumption by the rails app as well), but thanks for the tip.

I think this kind of info and example should definitely be in a README somewhere, especially with the release of 3.0.

**Comment by josh** [comment]
2438636bb553d4765eed1fcd4a5f9affe95cc060 should help you out a little.

**Comment by vincentwoo** [comment]
Oh, snap. Thanks!
