### ISSUE TITLE
UTF-8 without BOM in EncodingUtils#detect_html

### ISSUE THREAD

**Issue by llxff** [rails/sprockets#31]
Hello, 

Why does `EncodingUtils#detect_html` use ISO-8859-1 then `EncodingUtils#detect_css` use UTF-8 although `EncodingUtils#detect` use `Encoding.default_external` which is much better?

**Comment by josh** [comment]
The historically HTML's fallback encoding has been `ISO-8859-1`. CSS defines an explicit UTF-8 default fallback.

Since HTML's fallback is kinda fuzzy letting browsers take into account browser locale settings, it would probably be fine to use `Encoding.default_external` in that fallback case.

So that seems fine. Just curious what specific problem you've hit.

http://www.w3.org/html/wg/drafts/html/master/syntax.html
http://dev.w3.org/csswg/css-syntax/

**Comment by llxff** [comment]
Thank you for answer.

The problem is that most of IDEs and text editors save files in UTF-8 without BOM (which is neither required nor recommended for UTF-8). So, all html content in assets forced to ISO-8859-1 and browser doesn't render correctly non ascii characters (for example Russian language).

Problem example:

Template: https://github.com/llxff/sprockets_html_utf8/blob/master/app/assets/templates/test.html
Compiled result: https://blooming-depths-6065.herokuapp.com/assets/test-d1a8bb085402ed9a7c7120d13678683e19ca50f0c91d39d3381bf728de73cc79.html

**Comment by josh** [comment]
@llxff would you mind making a Pull Request to change the fallback to `default_external`. I'd accept that.

**Comment by llxff** [comment]
Ok

**Comment by josh** [comment]
Fixed by #32
