### ISSUE TITLE
ActionView::Template::Error ("\xA3" on UTF-8):

### ISSUE THREAD

**Issue by sweetppro** [rails/sprockets#353]
I get this strange crash in my Rails 4.2.6 & 5.0.0 apps when I use sprockets 3.6.2,3.6.3 or 3.70. 3.6.1 works just fine?

heres a stack trace:
```
-------------------------------
Backtrace:
-------------------------------

  app/views/store/order/new.html.erb:53:in `block in _app_views_store_ord=
er_new_html_erb___3816153851666412234_70199078146660'
  app/views/store/order/new.html.erb:17:in `_app_views_store_order_new_ht=
ml_erb___3816153851666412234_70199078146660'
  app/controllers/store/order_controller.rb:9:in `index'

ActionView::Template::Error ("\xA3" on UTF-8):
    50: 		<td>
    51: 			<p>
    52: 				<%= radio_button_tag 'payment_type', 'paypal_wps', @payment_type == 'paypal_wps', :id => 'paypal_wps' %>
    53: 				<%= image_tag "store/paypal.png", :alt => "Paypal WPS" %>
    54: 			</p>
    55: 			<p>
    56: 				<%= radio_button_tag 'payment_type', 'stripe', @payment_type == 'stripe', :id => 'stripe'%>
```

**Comment by schneems** [comment]
Please provide an example app that reproduces the problem. This will save maintainers time so they can spend it fixing your issues instead of trying to build a reproduction case from sparse instructions.

To create an example app, make an application locally that uses your same version of Sprockets. Add files to reproduce the problem. Once you've reproduced the problem add instructions on how to run your example app to a README.md file. Then commit everything to git and push to a new project on github. Once you've pushed your app add a link back to this issue.

**Comment by levilansing** [comment]
@sweetppro I think I ran into this a few weeks ago, seems extremely familiar. My problem was that I had a JS file with comments containing invalid UTF-8 sequences. `Mart�nez` to be exact. previous versions of sprockets didn't mind, but 3.6.3 was not having it. I fixed the file and all was good.

**Comment by sweetppro** [comment]
@levilansing you were right, it was a bad .js file.
:)

**Comment by schneems** [comment]
I think we should open up an issue. These types of problems should be easier to find and fix. The backtrace points at your view, while the problem was in a JS asset. Maybe this is covered by #335 but i'm not sure. If this is common enough to happen to the two of you (and i've seen it in the wild as well) then it is common enough to give a good error (if possible) on.

Glad you got things working, thanks for the issue!

**Comment by virsas** [comment]
i think i have this problem too. happening from version 3.6.2 upwards
ActionView::Template::Error ("\xEA" followed by "s" on UTF-8):

i checked all the files by creating the utf versions of them
for i in `ls -1`; do iconv -c -t UTF-8 < $i > $i.utf; done

and then i run diffs between the file and file.utf

that didnt give me anything. when i greped for "\xEA", i found it only in binary files , but those cannot be text encoded so hope those are not causing the issue.

Did check my js files, but no bad character there. Any way to point which file is causing this error ?

**Comment by alexcameron89** [comment]
@schneems I hit this issue today while playing around with adding a theme I purchased to an app:
```"\xEA" followed by "s" on UTF-8```

I'm still trying to figure out what's causing it, but if you want to see the error firsthand, I'll be happy to provide you access to it. It's a private repository, but I can add you as a member.
