### ISSUE TITLE
CoffeeScript 2 support

### ISSUE THREAD

**Issue by Fudoshiki** [rails/sprockets#528]
Hello, Sprockets 4 support babel-transpiller
Coffeescript 2 released. Now it compiles code to ES6

Can we make plans to integrate Coffescript 2 into Rails?

Related issue rails/ruby-coffee-script/issues/22

**Comment by halo** [comment]
With [this minimal change](https://github.com/halo/sprockets/compare/master...coffeescript2) I can use CoffeeScript 2 while still being able to use directives such as `#= require...`.

Unfortunately `import` statements are not working as they should due to the browser telling me `Uncaught ReferenceError: exports is not defined` where Babel produced this code.

```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

I think the problem is that Coffeescript produces ES5 whereas Babel expects ES6.

Also, source maps *seem* to work, but I think they *should* not work correctly. Because they are based on the intermediate es5 that coffeescript produced, rather than on the `.coffee` file.

Alternatively, I've been wondering whether there could not be a suffix transformer [similar to `.erb.coffee`](https://github.com/rails/sprockets/blob/9d945fbe1342136edd80888eba1c22f3d99d4ff9/lib/sprockets.rb#L177-L195) that processes something like `.es5.coffee` through CoffeeScript first and then through Babel.

**Comment by Fudoshiki** [comment]
I think this is irrelevant now
