### ISSUE TITLE
Fix homepage link on Rubygems

### ISSUE THREAD

**Issue by greysteil** [rails/sprockets#557]
### Expected behavior

Homepage link on [rubygems](https://rubygems.org/gems/sprockets) should be https://github.com/rails/sprockets.

### Actual behavior

Homepage link is http://getsprockets.org/

Solution is to log into Rubygems and update it manually there. For some reason it's not picking up the updated version in the gemspec 🤷‍♂️

**Comment by schneems** [comment]
I can't update the homepage. Not sure why it's not being picked up via gemspec for 3.x or 4.x

![](https://www.dropbox.com/s/m5a2a2hsf4jrqh0/Screenshot%202018-06-19%2012.26.38.png?raw=1)

Actually, I bet its because I pushed 2.x last. I can update the branch, but seems a bit heavy handed to cut a release just for that change. It should update next time I release another version with a fixed gemspec?

**Comment by schneems** [comment]
Closing for now. I updated the gemspec on the `2.x` branch. They all now point to the same place. It will get updated the next time I cut any version release (i think).

**Comment by greysteil** [comment]
👍 - I've also created https://github.com/rubygems/rubygems.org/pull/1735 to fix the issue with Rubygems.

**Comment by schneems** [comment]
Thanks! I opened an issue to raise awareness, but actually making a pr is 💯 https://github.com/rubygems/rubygems.org/issues/1734
