### ISSUE TITLE
Switch to terser for tests as well

### ISSUE THREAD

**Issue by pravi** [rails/sprockets#745]
### Expected behavior

sprockets should test with terser gem instead of uglifier as this is the recommended option. See https://github.com/rails/sprockets/pull/713

### Actual behavior
uglifier is still used in tests https://github.com/rails/sprockets/blob/master/sprockets.gemspec#L35

### System configuration

- Sprockets version
- Ruby version

**Comment by rafaelfranca** [comment]
There is no terser compressor inside the sprockets codebase, but there is a uglifier compressor inside sprockets. That is why we are testing with uglifier but not terser. Since we don't plan to include the terser compressor in the sprockets codebase, and the terser compressor is already being tested in the terser gem, I think it doesn't make sense to test this again.

Thank you for the suggestion though.

**Comment by Faq** [comment]
When remove 'uglifier', just add in prodiction.rb
```
require "terser"

Sprockets.register_compressor("application/javascript", :terser, Terser::Compressor)
config.assets.js_compressor = :terser
```
