### ISSUE TITLE
JavaScript asset not found if directory has extension (.js)

### ISSUE THREAD

**Issue by TiteiKo** [rails/sprockets#75]
See original issues : rails/rails#18859 and sstephenson/sprockets#706

**Error is still present in sprockets 3.2.0**

Problem is when the directory is named something.js (which is quite a common thing to do in the js community)

So you'd want to require it like this : 

```
//= require something.js
```

But you'd get the error below : 
```
Sprockets::FileNotFound - couldn't find file 'something.js' with type 'application/javascript':
```

Ugly workaround : adding a second .js in the requirement seems to trick sprockets

```
//= require something.js.js
```

**Comment by ajb** [comment]
Normally I wouldn't comment with just a :+1:, but since nobody else has...

**Comment by tpedelose-ts** [comment]
Currently running into this issue. However, the 'hack' posted above doesn't seem to work for me.

After adding VideoJs to my project I needed to rename the directory with either a dash or an underscore to get sprockets to use it. This works fine as long as you don't expect to be using any plugins - they will install 'video.js' as a dependency when it is not found.

**Comment by rafaelfranca** [comment]
Could you check with sprockets 4?

**Comment by robin850** [comment]
Hi there!

Sorry if I'm missing something obvious but did you try with:

~~~javascript
//= require_directory ./something.js
~~~

**Comment by schneems** [comment]
I can confirm `//= require_directory ./something.js` works and `//= require ./something.js` does not work. 

I think this is a bad experience, i'm not sure what it takes to fix, ideally we would either have it do the right thing (tm) or at very least raise an instructive error. I'll dig into to how difficult/expensive fixing this will be.

**Comment by rafaelfranca** [comment]
I believe it is due the index aliases features. Check some of the last
issues and pr from Josh

**Comment by schneems** [comment]
So it looks like if you don't have a `.js` extension in your folder, it wouldn't work anyway.

```
app/
  assets/
    bar/
      bar.js
```

You cannot

```js
//= require bar
```

or

```js
//= require bar.js
```

Both of them will fail. The only thing that would be valid is 

```js
//= require bar/bar.js
```

Likewise if you've got

```
app/
  assets/
    foo.js/
      foo.js
```

Then this will work:

```js
//= require foo.js/foo.js
```

I think the correct thing to do here (unless i'm missing something) would be to raise an error telling you that `//= require foo.js` is a directory and that you should use the `require_directory` directive instead.

**Comment by rafaelfranca** [comment]
When you have:

```
app/
  assets/
    foo/
      index.js
```

```
//= require foo.js
```

Will load `foo/index.js`, that is the index aliases feature and I think this is related to this feature. Have you checked if that is working at sprockets 4? We changed the aliases feature.

**Comment by schneems** [comment]
I documented this "index.js" behavior. Maybe we can do more to notify conflicts. If you have ideas please open up a new issue.

**Comment by schneems** [comment]
Realized this is slightly different from what I documented. Can you please check with Sprockets 4 to see if this is still an issue? If so I can re-open. Please provide an example app that reproduces the problem.

**Comment by schneems** [comment]
The issue still exists in sprockets 3 but is resolved in master, please use the Sprockets 4 beta. If you want to find and backport the fix in a PR, i'll be happy to merge

**Comment by schneems** [comment]
And...because no one gave me an example app, i'm finding out that it is broken on Sprockets master, but there was an error with the bug repro instructions in the other issue. Going to comment on other linked  issue for now.

**Comment by schneems** [comment]
Wanted to comment here too: 

Okay the issue is that you're asking for an asset `favico.js` and that asset does not exist on disk anywhere. There are two other assets that do exist, a `favico.js.js` and a `favico.js/favico.js`

![](https://www.dropbox.com/s/qs7ek8yhcoa779n/Screenshot%202016-10-10%2011.28.30.png?dl=1)

Right now we have a few options. 

1) The author of that lib can add an `index.js` under `favico.js` folder and it will work because sprockets assumes index files will take the name of their parent directories. 

2) You can work around this yourself by using either of the above file names I provided in the require.

```
//= require favico.js/favico.js
```

Works and

```
//= require favico.js.js
``` 

Works because those are literally the things on disk, Sprockets has no special logic for files inside of a directory with an extension.

3) We can add behavior so that when we are searching a directory that ends in a `.<extension>` then we also check for a file that is ending in `.<extension>.<extension>`. Is that an industry standard convention? Are does every `<blank>.js` library that has a `<blank>.js` directory do that? If so I'm happy to accept a patch for it, however it adds complexity and may add confusion.

## Moving forwards

(2) is the easiest for the user to get working right now but doesn't solve the systemic problem, (1) is the second easiest for this specific case and prevents future users from hitting that issue but it might be hard to get ever JS maintainer to accept adding an `index.js` file "just because" sprockets needs it (even though it's apparently a node standardhttps://github.com/rails/sprockets#index-files-are-proxies-for-folders), (3) we can do if there is sufficient interest and someone gives me a PR.
